name: Build Mod

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare libs
        run: mkdir -p libs

      - name: Download SMAPI
        run: |
          wget https://github.com/Pathoschild/SMAPI/releases/latest/download/SMAPI-installer.zip -O smapi.zip
          unzip -o smapi.zip -d smapi
          find smapi -type f -name "StardewModdingAPI.dll" -exec cp {} libs/ \;
          ls libs

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0.x

      - name: Build
        run: dotnet build --configuration Release

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: FloatingCursorMod
          path: bin/Release/net6.0/